name: Build DLL

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Add MSVC to PATH
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    - name: Compile DLL
      run: |
        cl.exe /LD version.cpp /Fe:version.dll /link /EXPORT:GetFileVersionInfoA=GetFileVersionInfoA_Proxy /EXPORT:GetFileVersionInfoSizeA=GetFileVersionInfoSizeA_Proxy /EXPORT:GetFileVersionInfoSizeW=GetFileVersionInfoSizeW_Proxy /EXPORT:GetFileVersionInfoW=GetFileVersionInfoW_Proxy /EXPORT:VerQueryValueA=VerQueryValueA_Proxy /EXPORT:VerQueryValueW=VerQueryValueW_Proxy
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: version-dll
        path: version.dll
